/* Atlas depth pack v3: learn/do/time per node. Key = roadmapId::Node Title */
const DEPTH = {
"cyber-security::The Hacker Mindset": {t:"3 days", l:["What ethical hacking is and why permission is everything","The hacker mindset: curiosity plus persistence","How bug bounty and pentesting differ"], d:["Read 5 HackerOne Hacktivity reports end to end","Write down your personal rules of engagement","Join one security community (Discord or Reddit)"]},
"cyber-security::Computer & Network Basics": {t:"2 weeks", l:["How data travels: packets, frames, encapsulation","The OSI model layers and what lives at each","What an IP address and port really are"], d:["Draw the OSI model from memory","Explain to a friend how a website loads","Run ip addr and read every line"]},
"cyber-security::Linux Command Line": {t:"3 weeks", l:["Navigation, files, and the 20 core commands","Pipes, redirection, and chaining tools","man pages: reading documentation like a pro"], d:["Finish OverTheWire Bandit levels 0-10","Do 10 daily terminal challenges","Navigate your whole system without a GUI for a day"]},
"cyber-security::Networking: TCP/IP & DNS": {t:"2 weeks", l:["TCP vs UDP and the three-way handshake","DNS resolution step by step","Common ports and what runs on them"], d:["Capture a DNS lookup in Wireshark","Memorize the top 20 ports","Explain CIDR notation to someone"]},
"cyber-security::Wireshark": {t:"1 week", l:["Capture filters vs display filters","Following TCP streams","Spotting anomalies in traffic"], d:["Follow 3 HTTP streams in a sample capture","Find the DNS queries in a capture","Filter traffic to one single host"]},
"cyber-security::Programming for Hackers": {t:"1 week", l:["Why hackers code: automation over manual work","Reading code vs writing code","Where to apply scripting in attacks"], d:["Automate one boring task you do","Read a small open-source tool's code","Write a port checker in 20 lines"]},
"cyber-security::Python": {t:"4 weeks", l:["Syntax, functions, and data structures","The requests library and sockets","Error handling and virtual environments"], d:["Write a subdomain brute-forcer","Build a simple port scanner","Automate a recon task with requests"]},
"cyber-security::Bash Scripting": {t:"2 weeks", l:["Variables, loops, and conditionals","Pipes and command substitution","Writing reusable scripts"], d:["Script your recon workflow","Write a log analyzer with grep and awk","Automate backups of your notes"]},
"cyber-security::Web Tech: HTML & JS": {t:"2 weeks", l:["HTML structure and forms","JavaScript DOM manipulation","How cookies and sessions work"], d:["Build a login form by hand","Inspect 5 sites' devtools network tabs","Write JS that reads and writes cookies"]},
"cyber-security::Reconnaissance": {t:"2 weeks", l:["Passive vs active recon","The recon methodology: enumerate everything","OPSEC: staying quiet while looking"], d:["Map a target's subdomains passively","Build a recon checklist","Document findings like a pro"]},
"cyber-security::OSINT": {t:"2 weeks", l:["People, companies, and infrastructure OSINT","Google dorking operators","Social media intelligence"], d:["Profile a fictional target from public data","Master 10 Google dorks","Try theHarvester on a domain you own"]},
"cyber-security::Nmap Scanning": {t:"2 weeks", l:["Scan types: SYN, connect, UDP","Service and version detection","The Nmap Scripting Engine"], d:["Scan your home lab with -sC -sV","Run 5 NSE scripts and read outputs","Time a full port scan and optimize it"]},
"cyber-security::Web Hacking": {t:"3 weeks", l:["How web apps handle input","The OWASP Top 10 overview","Methodology: map then attack"], d:["Complete 3 PortSwigger labs","Map a Juice Shop instance fully","Keep a bug journal"]},
"cyber-security::Burp Suite": {t:"2 weeks", l:["Proxy, Repeater, Intruder","Intercepting and modifying requests","Scope and project organization"], d:["Intercept your own logins","Replay 10 requests in Repeater","Run an Intruder attack on Juice Shop"]},
"cyber-security::SQL Injection": {t:"3 weeks", l:["How SQL queries are built","Union-based and blind injection","Bypassing weak filters"], d:["Finish PortSwigger SQLi labs","Exploit SQLi in Juice Shop","Try sqlmap on a lab target"]},
"cyber-security::XSS & Broken Access Control": {t:"3 weeks", l:["Reflected, stored, and DOM XSS","IDOR patterns and testing","Forcing browse and privilege escalation"], d:["Finish PortSwigger XSS labs","Find IDORs in a lab app","Write 3 XSS payloads from scratch"]},
"cyber-security::Exploitation": {t:"3 weeks", l:["Vulnerability vs exploit vs payload","Staged vs stageless payloads","Post-exploitation basics"], d:["Exploit Metasploitable with MSF","Get 3 different reverse shells working","Document an exploit chain"]},
"cyber-security::Metasploit Framework": {t:"2 weeks", l:["Modules: auxiliary, exploit, payload","Meterpreter essentials","msfvenom payload generation"], d:["Own Metasploitable 3","Generate 3 payload types","Practice pivoting basics"]},
"cyber-security::Password Attacks": {t:"2 weeks", l:["Hash types and identification","Dictionary vs brute force vs rules","Password spraying vs credential stuffing"], d:["Crack 10 hashes with hashcat","Run a Hydra attack on your lab","Build a custom wordlist with cewl"]},
"cyber-security::Privilege Escalation": {t:"4 weeks", l:["Linux: SUID, sudo, cron, kernels","Windows: services, tokens, AlwaysInstallElevated","Enumeration before exploitation"], d:["Root 5 VulnHub Linux boxes","Run LinPEAS and read every finding","Escalate on 3 Windows lab machines"]},
"cyber-security::Go Pro": {t:"ongoing", l:["Career paths: pentest, bounty, SOC","Building a public portfolio","Interview and report skills"], d:["Publish your first writeup","Do a mock pentest report","Apply to 3 junior roles or internships"]},
"cyber-security::Bug Bounty Hunting": {t:"ongoing", l:["Platforms: HackerOne, Bugcrowd, Intigriti","Scope reading and program selection","Duplicate avoidance"], d:["Read 20 disclosed reports","Hunt on 2 VDP programs","Submit your first report"]},
"cyber-security::Reports & Writeups": {t:"1 week", l:["Anatomy of a great report","Severity and impact writing","Proof of concept discipline"], d:["Rewrite a public report in your words","Write a full PoC for a lab bug","Get feedback on your writing"]},
"frontend::Internet & How the Web Works": {t:"3 days", l:["DNS, HTTP requests and responses","How browsers render pages","Client vs server responsibilities"], d:["Trace a page load in devtools","Explain DNS to a friend","Read raw HTTP with curl -v"]},
"frontend::HTML": {t:"1 week", l:["Semantic tags and document structure","Forms and inputs","Accessibility basics"], d:["Build a tribute page","Make a form with every input type","Validate with the W3C checker"]},
"frontend::CSS": {t:"3 weeks", l:["Box model, flexbox, grid","Responsive design and media queries","Animations and transitions"], d:["Clone a landing page","Build a responsive navbar","Recreate 3 animations from scratch"]},
"frontend::JavaScript (ES6+)": {t:"6 weeks", l:["Variables, functions, arrays, objects","DOM manipulation and events","Async: promises and fetch"], d:["Build a todo app","Fetch and render an API","Complete 30 JS exercises"]},
"frontend::Git & GitHub": {t:"1 week", l:["Commit, branch, merge","Remotes and pull requests","Resolving conflicts"], d:["Push 5 projects to GitHub","Open a PR on an open-source repo","Fix a merge conflict"]},
"frontend::npm & Vite Tooling": {t:"1 week", l:["package.json and dependencies","Dev servers and hot reload","Build vs dev mode"], d:["Scaffold 3 Vite projects","Install and use 5 libraries","Debug a broken install"]},
"frontend::React": {t:"6 weeks", l:["Components, props, state","Hooks: useState, useEffect","Data fetching patterns"], d:["Build a weather app","Rebuild the todo app in React","Fetch from 3 different APIs"]},
"frontend::TypeScript": {t:"3 weeks", l:["Types, interfaces, generics","Typing React components","Strict mode discipline"], d:["Convert a JS project to TS","Type 10 utility functions","Fix 20 type errors"]},
"frontend::Testing with Vitest": {t:"2 weeks", l:["Unit vs integration tests","Testing components","Mocking APIs"], d:["Write tests for your todo app","Reach 80% coverage on a project","Test 5 edge cases"]},
"frontend::Deploy: Vercel & Netlify": {t:"3 days", l:["Build pipelines and environments","Custom domains and HTTPS","Preview deployments"], d:["Deploy 3 projects","Connect a custom domain","Set up preview deploys"]},
"backend::Pick a Language": {t:"4 weeks", l:["Syntax and standard library","Error handling","One language deeply"], d:["Build a CLI tool","Solve 20 coding problems","Read a framework's source"]},
"backend::REST APIs": {t:"3 weeks", l:["Resources, verbs, status codes","Request validation","Versioning and docs"], d:["Build a CRUD API","Document it with OpenAPI","Consume your own API"]},
"backend::SQL Databases": {t:"4 weeks", l:["Schema design and relations","JOINs and aggregations","Indexes and performance"], d:["Design a blog schema","Write 30 SQL queries","Optimize a slow query"]},
"backend::Auth: JWT & OAuth": {t:"2 weeks", l:["Sessions vs tokens","Password hashing with bcrypt","OAuth flows"], d:["Add JWT auth to your API","Implement OAuth login","Break your own auth in a lab"]},
"backend::Caching with Redis": {t:"1 week", l:["When and what to cache","TTL and invalidation","Redis data structures"], d:["Cache 3 slow endpoints","Measure the speedup","Handle cache misses"]},
"backend::Docker Basics": {t:"2 weeks", l:["Images vs containers","Dockerfiles that stay small","Volumes and networks"], d:["Dockerize your API","Write a compose file","Shrink an image under 100MB"]},
"backend::Testing & CI": {t:"2 weeks", l:["Unit and integration tests","GitHub Actions pipelines","Keeping builds green"], d:["Add CI to a project","Write 20 backend tests","Make a failing build pass"]},
"devops::Linux & Scripting": {t:"3 weeks", l:["Terminal fluency","Bash scripting","System administration"], d:["Live in the terminal for a week","Script 5 admin tasks","Harden an SSH server"]},
"devops::Git Deeply": {t:"1 week", l:["Branching strategies","Rebase vs merge","Hooks and submodules"], d:["Rebase a messy branch","Write a pre-commit hook","Recover a deleted commit"]},
"devops::CI/CD: GitHub Actions": {t:"2 weeks", l:["Workflows, jobs, runners","Secrets and environments","Reusable workflows"], d:["Build a full CI pipeline","Deploy on every merge","Cache dependencies"]},
"devops::Docker": {t:"3 weeks", l:["Multi-stage builds","Networking and volumes","Registries"], d:["Multi-stage your builds","Run a 3-service stack","Push to a registry"]},
"devops::Kubernetes": {t:"6 weeks", l:["Pods, deployments, services","ConfigMaps and secrets","Helm charts"], d:["Deploy an app to k3s","Write your own manifests","Break and fix a cluster"]},
"devops::Cloud: AWS": {t:"4 weeks", l:["EC2, S3, VPC basics","IAM least privilege","Billing awareness"], d:["Host a site on EC2","Build a VPC from scratch","Set billing alarms"]},
"devops::Terraform (IaC)": {t:"3 weeks", l:["Resources and state","Modules","Workspaces"], d:["Provision a VPC with Terraform","Import existing infra","Write a reusable module"]},
"devops::Monitoring": {t:"2 weeks", l:["Metrics vs logs vs traces","Alerting that matters","Dashboards people read"], d:["Monitor your own server","Create 5 useful alerts","Build a Grafana dashboard"]},
"python::Python Basics": {t:"2 weeks", l:["Syntax and data types","Loops and functions","Modules and pip"], d:["Solve 30 beginner problems","Build a calculator","Read the official tutorial fully"]},
"python::OOP & Modules": {t:"2 weeks", l:["Classes and objects","Inheritance and dunder methods","Packaging code"], d:["Model a card game with classes","Refactor scripts into modules","Publish a tiny package"]},
"python::Virtual Envs & pip": {t:"3 days", l:["Why isolation matters","venv and pip workflows","requirements files"], d:["Create 5 isolated envs","Fix a dependency conflict","Freeze a working env"]},
"python::Requests & APIs": {t:"1 week", l:["GET, POST, headers, auth","JSON handling","Rate limits and retries"], d:["Build an API client","Scrape a public API","Handle 3 error cases"]},
"python::Automation Scripts": {t:"2 weeks", l:["os, shutil, pathlib","Scheduling with cron","Logging"], d:["Automate file organization","Write a backup script","Schedule it with cron"]},
"python::Web: FastAPI": {t:"3 weeks", l:["Routes and Pydantic models","Dependency injection","Async endpoints"], d:["Build a todo API","Add auth to it","Write API tests"]},
"python::Data: pandas & numpy": {t:"3 weeks", l:["DataFrames and series","Filtering and grouping","Basic plotting"], d:["Analyze a CSV dataset","Answer 10 questions with pandas","Make 5 charts"]},
"linux::Install & First Terminal": {t:"3 days", l:["Choosing a distro","The filesystem hierarchy","First 20 commands"], d:["Install Ubuntu in a VM","Take a snapshot","Break it, then restore"]},
"linux::Files & Permissions": {t:"1 week", l:["chmod, chown, umask","Users and groups","SUID demystified"], d:["Fix 10 permission puzzles","Explain SUID to someone","Audit a directory tree"]},
"linux::Text Processing": {t:"2 weeks", l:["grep, sed, awk essentials","Pipes and redirection","Regex fluency"], d:["Parse 3 log files","One-line 5 data tasks","Learn 10 regex patterns"]},
"linux::Processes & systemd": {t:"1 week", l:["ps, top, kill","systemd units and timers","Logs with journalctl"], d:["Write a systemd service","Debug a failing service","Schedule with timers"]},
"linux::Networking Tools": {t:"1 week", l:["ssh, scp, curl","ss, ip, ping","Firewalls with ufw"], d:["SSH key-only login","Transfer files with scp","Close every open port"]},
"linux::Bash Scripting": {t:"2 weeks", l:["Scripts that do real work","Functions and arguments","Error handling"], d:["Automate your setup","Write a deploy script","Add logging to scripts"]},
"linux::System Administration": {t:"3 weeks", l:["Updates and packages","Backups that restore","Basic hardening"], d:["Harden a fresh VPS","Set up automated backups","Monitor disk and memory"]},
"bug-bounty::The Hunter Mindset": {t:"3 days", l:["How bounty platforms and scopes work","Severity ratings and payouts","Rules of engagement"], d:["Read 10 disclosed reports","Compare 3 programs' scopes","Write your hunter rules"]},
"bug-bounty::Web Fundamentals, Deep": {t:"2 weeks", l:["HTTP at expert level","Browsers and same-origin policy","Modern web frameworks"], d:["Map a complex SPA","Trace every request of a login","Document an app's attack surface"]},
"bug-bounty::HTTP Deep Dive": {t:"1 week", l:["Methods beyond GET and POST","Headers that matter for security","CORS misconfigurations"], d:["Tamper every header in Burp","Find 3 CORS issues in labs","Replay requests with curl"]},
"bug-bounty::JavaScript for Hackers": {t:"2 weeks", l:["DOM sinks and sources","Frameworks and XSS filters","Prototype pollution basics"], d:["Audit 5 JS files for sinks","Write DOM XSS payloads","Trace data flow in a SPA"]},
"bug-bounty::Recon at Scale": {t:"2 weeks", l:["Automation pipelines","Asset monitoring","ASN and cloud recon"], d:["Build an auto-recon script","Monitor a target for a week","Enumerate an ASN"]},
"bug-bounty::Subdomain Enumeration": {t:"1 week", l:["Passive vs active techniques","Permutation and brute force","Validating live hosts"], d:["Enumerate 3 bug bounty targets","Build a subdomain pipeline","Find forgotten subdomains"]},
"bug-bounty::Content Discovery": {t:"1 week", l:["Wordlist strategy","Status code interpretation","API endpoint discovery"], d:["Fuzz 5 targets","Build a custom wordlist","Find hidden API versions"]},
"bug-bounty::Vulnerability Classes": {t:"ongoing", l:["OWASP Top 10 by heart","New bug classes yearly","Reading research blogs"], d:["Study one class per week","Reproduce 5 CVEs in labs","Summarize research papers"]},
"bug-bounty::IDOR & Access Control": {t:"2 weeks", l:["IDOR patterns in APIs","Multi-step access flaws","Mass assignment"], d:["Hunt IDORs in 3 lab apps","Test every role combination","Chain IDOR to account takeover"]},
"bug-bounty::SSRF & XXE": {t:"2 weeks", l:["Blind SSRF techniques","Cloud metadata attacks","XXE payload craft"], d:["Exploit SSRF in labs","Hit a metadata endpoint","Bypass 3 SSRF filters"]},
"bug-bounty::Race Conditions": {t:"2 weeks", l:["Single vs multi-endpoint races","Turbo Intruder basics","Impact: from coupons to funds"], d:["Reproduce 3 race labs","Write a race exploit script","Measure timing windows"]},
"bug-bounty::Hunter Methodology": {t:"ongoing", l:["Checklists per bug class","Note-taking systems","Avoiding duplicates"], d:["Build your methodology doc","Time-box your hunts","Review hunts weekly"]},
"bug-bounty::Target Selection": {t:"3 days", l:["New vs mature programs","Scope size signals","Your unfair advantages"], d:["Rank 10 programs","Pick 2 and commit a month","Track your hit rate"]},
"bug-bounty::Report Writing": {t:"1 week", l:["Reproduction steps that work","Impact statements","Severity justification"], d:["Rewrite 5 public reports","Get a peer review","Submit and iterate"]},
"networking::Networks 101": {t:"3 days", l:["What a network really is","Packets vs frames vs segments","Your home network map"], d:["Draw your home network","List every device's IP","Explain DHCP to someone"]},
"networking::OSI & TCP/IP": {t:"2 weeks", l:["Each layer's job","Encapsulation walkthrough","TCP vs UDP trade-offs"], d:["Label a packet capture by layer","Teach the OSI model","Compare TCP and UDP live"]},
"networking::IP & Subnetting": {t:"2 weeks", l:["Binary and CIDR math","Subnet design","VLSM basics"], d:["Subnet 20 networks by hand","Design a company network","Race a subnet calculator"]},
"networking::DNS Deep Dive": {t:"1 week", l:["Record types master list","Resolution chain","DNS security: spoofing, tunneling"], d:["Query every record type","Trace a full resolution","Spot DNS tunneling in a capture"]},
"networking::Routing & Switching": {t:"2 weeks", l:["MAC vs IP forwarding","Routing tables","VLANs"], d:["Read your router's table","Trace 5 routes","Explain a traceroute"]},
"networking::Wireshark Mastery": {t:"2 weeks", l:["Advanced display filters","Statistics and IO graphs","Troubleshooting with packets"], d:["Solve 10 analysis challenges","Graph a slow transfer","Find the anomaly"]},
"networking::Network Services": {t:"1 week", l:["DHCP handshake","NAT types","Common service ports"], d:["Watch a DHCP exchange","Map NAT on your router","List listening services"]},
"networking::Firewalls & NAT": {t:"1 week", l:["Stateful vs stateless","Rule order matters","Port forwarding"], d:["Write iptables rules","Forward a port","Block and allow by rule"]},
"cloud::Cloud Concepts": {t:"3 days", l:["Regions and availability zones","Shared responsibility model","Cloud pricing basics"], d:["Compare 3 providers","Draw the responsibility split","Estimate a workload's cost"]},
"cloud::AWS Core Services": {t:"3 weeks", l:["EC2, S3, VPC, IAM essentials","Security groups","The console and CLI"], d:["Launch and secure an EC2","Build a VPC","Use the CLI daily"]},
"cloud::IAM Deep Dive": {t:"2 weeks", l:["Users, roles, policies","Least privilege design","Policy evaluation logic"], d:["Write 5 custom policies","Audit an account's IAM","Break and fix a policy"]},
"cloud::S3 & Storage": {t:"1 week", l:["Bucket policies vs ACLs","Versioning and encryption","Common leak patterns"], d:["Audit bucket permissions","Find public buckets in labs","Enable logging everywhere"]},
"cloud::Cloud Security": {t:"3 weeks", l:["Attacker cloud methodology","Privilege escalation paths","Logging and detection"], d:["Run Prowler on a lab account","Escalate privileges in a CTF","Read CloudTrail logs"]},
"cloud::Common Misconfigurations": {t:"2 weeks", l:["The top 10 cloud mistakes","How attackers find them","Remediation patterns"], d:["Scan a lab account","Fix every finding","Write a hardening checklist"]},
"cloud::ScoutSuite & Prowler": {t:"1 week", l:["Automated auditing","Reading the reports","Continuous monitoring"], d:["Audit 2 lab accounts","Triage 20 findings","Automate weekly scans"]},
"linux::Linux Fundamentals": {t:"10 weeks", l:["The full journey from install to hardening","How every layer of Linux fits together"], d:["Install Linux in a VM today","Finish one category per week"]},
"linux::Installation & Environment": {t:"1 week", l:["Choosing and installing a distro","First contact with the terminal"], d:["Install Ubuntu in VirtualBox","Take a snapshot before experimenting"]},
"linux::Linux Distributions": {t:"2 days", l:["Debian vs Arch vs RHEL families","Desktop vs server editions"], d:["Try 2 distros in VMs","Read 3 distro wikis"]},
"linux::Virtual Machines": {t:"2 days", l:["How virtualization works","Snapshots and clones"], d:["Install VirtualBox","Snapshot, break, restore"]},
"linux::Terminal Setup": {t:"2 days", l:["Terminal emulators and shells","Basic customization"], d:["Try bash and zsh","Customize your prompt"]},
"linux::Filesystem Layout": {t:"2 days", l:["The FHS standard","Where everything lives"], d:["Explore /, /etc, /var","Draw the tree from memory"]},
"linux::File Operations": {t:"3 days", l:["cp, mv, rm, mkdir, touch","Wildcards and brace expansion"], d:["Organize 100 files by script","Master 5 wildcards"]},
"linux::chmod, chown, umask": {t:"1 week", l:["Octal and symbolic modes","Ownership and default masks"], d:["Fix 10 permission puzzles","Predict umask outcomes"]},
"linux::ACLs & Special Bits": {t:"3 days", l:["setfacl and getfacl","SUID, SGID, sticky bit"], d:["Set an ACL","Find SUID binaries"]},
"linux::grep & Regex": {t:"1 week", l:["Regex syntax essentials","grep flags that matter"], d:["Solve 15 regex puzzles","Grep a 10k-line log"]},
"linux::sed & awk": {t:"1 week", l:["sed substitutions","awk field processing"], d:["Rewrite 5 files with sed","Summarize a CSV with awk"]},
"linux::sort, uniq, cut, tr": {t:"3 days", l:["Sorting and deduping","Cutting columns, translating chars"], d:["One-line 5 data tasks","Chain all four tools"]},
"linux::Pipes & Redirection": {t:"3 days", l:[">, >>, 2>, and pipes","stdin, stdout, stderr"], d:["Build a 5-stage pipeline","Redirect errors to a file"]},
"linux::Process Inspection": {t:"3 days", l:["ps, top, htop","Reading load averages"], d:["Find the hungriest process","Kill by pattern safely"]},
"linux::Signals & Job Control": {t:"3 days", l:["SIGTERM vs SIGKILL","bg, fg, jobs, nohup"], d:["Stop and resume a job","Run a task with nohup"]},
"linux::systemd Services": {t:"1 week", l:["Units, targets, dependencies","systemctl fluency"], d:["Write a service file","Debug a failed service"]},
"linux::Resource Monitoring": {t:"3 days", l:["CPU, memory, disk, IO","Bottleneck thinking"], d:["Diagnose a slow VM","Set up a monitoring alias"]},
"linux::ip & ss": {t:"3 days", l:["ip addr, ip route","ss listening sockets"], d:["Map your interfaces","List every listening port"]},
"linux::ping & traceroute": {t:"2 days", l:["ICMP basics","Reading hop latency"], d:["Trace 5 routes","Compare ping times"]},
"linux::dig & nslookup": {t:"2 days", l:["Querying record types","Using specific resolvers"], d:["Dig every record type","Trace a full resolution"]},
"linux::curl & tcpdump": {t:"1 week", l:["curl flags for APIs","tcpdump filters"], d:["curl 5 APIs","Capture a handshake"]},
"linux::Variables & Quoting": {t:"3 days", l:["Variables and scope","Single vs double quotes"], d:["Write 5 quoted snippets","Debug a quoting bug"]},
"linux::Conditions & Loops": {t:"1 week", l:["test, if, case","for, while, until"], d:["Script a file organizer","Loop over 100 hosts"]},
"linux::Functions": {t:"3 days", l:["Defining and calling","Return values and args"], d:["Refactor scripts into functions","Build a function library"]},
"linux::Exit Codes & set -euo": {t:"2 days", l:["Exit codes that mean something","Strict mode scripting"], d:["Add error handling","ShellCheck 3 scripts"]},
"linux::Users & Groups": {t:"3 days", l:["useradd, usermod, groups","The sudoers file"], d:["Create 3 users with roles","Configure passwordless sudo"]},
"linux::Package Management": {t:"3 days", l:["apt update vs upgrade","Repos and PPAs"], d:["Install from 3 sources","Clean a broken apt"]},
"linux::Logs & journald": {t:"3 days", l:["journalctl queries","Log rotation basics"], d:["Find a boot error","Follow logs live"]},
"linux::SSH Hardening": {t:"3 days", l:["Key-only auth","sshd_config essentials"], d:["Disable password login","Harden a fresh VPS"]},
"linux::Cron Jobs": {t:"2 days", l:["Crontab syntax","Logging cron output"], d:["Schedule 3 jobs","Debug a silent cron"]},
"linux::Linux Security": {t:"3 weeks", l:["Threat model for a Linux box","Defense in depth"], d:["Audit a VPS","Write a hardening checklist"]},
"linux::Least Privilege": {t:"3 days", l:["Why root is dangerous","Capability thinking"], d:["Audit sudo rights","Remove 3 excess grants"]},
"linux::Sudo Configuration": {t:"2 days", l:["visudo and sudoers.d","Command restrictions"], d:["Restrict a user to 2 commands","Test the restrictions"]},
"linux::System Hardening": {t:"1 week", l:["Attack surface reduction","Sysctl hardening"], d:["Run Lynis audit","Apply 10 hardenings"]},
"linux::Auditing & Monitoring": {t:"1 week", l:["auditd rules","File integrity monitoring"], d:["Watch /etc with auditd","Set up AIDE"]},
"cyber-security::File Navigation": {t:"3 days", l:["cd, ls, find at speed","Globbing patterns"], d:["Navigate blindfolded","Find 10 files by pattern"]},
"cyber-security::Users & Permissions": {t:"3 days", l:["chmod, chown essentials","sudo and privilege model"], d:["Lock down a directory","Explain SUID"]},
"cyber-security::Subnetting Basics": {t:"1 week", l:["CIDR notation","Subnet math by hand"], d:["Subnet 10 networks","Beat a subnet calculator"]},
"cyber-security::Common Ports": {t:"3 days", l:["The 20 ports that matter","Service fingerprinting"], d:["Memorize top ports","Map ports to services"]},
"cyber-security::Display Filters": {t:"3 days", l:["Filter syntax","Protocol filters"], d:["Write 10 filters","Isolate one host"]},
"cyber-security::Follow TCP Streams": {t:"2 days", l:["Rebuilding sessions","Spotting credentials"], d:["Follow 3 streams","Find a password"]},
"cyber-security::Requests & Web": {t:"1 week", l:["GET, POST, sessions","Headers and auth"], d:["Script a login flow","Scrape 3 pages"]},
"cyber-security::Scripting Tools": {t:"1 week", l:["argparse for CLIs","Sockets basics"], d:["Build a port scanner","Add CLI args"]},
"cyber-security::DOM & Events": {t:"3 days", l:["Selecting elements","Event listeners"], d:["Build an interactive page","Trace 5 events"]},
"cyber-security::Google Dorking": {t:"3 days", l:["Advanced operators","Finding exposed data"], d:["Master 12 dorks","Find 3 exposures"]},
"cyber-security::Social Media Intel": {t:"2 days", l:["Profile analysis","Username enumeration"], d:["Map a test profile","Try 3 OSINT tools"]},
"cyber-security::Scan Types": {t:"3 days", l:["SYN vs connect vs UDP","Stealth considerations"], d:["Run 3 scan types","Compare the noise"]},
"cyber-security::NSE Scripts": {t:"3 days", l:["Script categories","Safe vs intrusive"], d:["Run 8 NSE scripts","Read 3 script sources"]},
"cyber-security::Proxy & Intercept": {t:"3 days", l:["Setting up the proxy","Intercepting HTTPS"], d:["Intercept your logins","Modify 5 requests"]},
"cyber-security::Repeater & Intruder": {t:"1 week", l:["Manual replay","Automated attacks"], d:["Replay 10 requests","Fuzz a parameter"]},
"cyber-security::Union-Based": {t:"1 week", l:["Column counting","Data extraction"], d:["Finish 3 labs","Dump a table"]},
"cyber-security::Blind SQLi": {t:"2 weeks", l:["Boolean inference","Time-based exfil"], d:["Solve 3 blind labs","Use sqlmap wisely"]},
"cyber-security::Reflected & Stored XSS": {t:"1 week", l:["Payload contexts","Stored persistence"], d:["Pop 5 alerts","Steal a cookie in lab"]},
"cyber-security::IDOR Testing": {t:"3 days", l:["Predictable identifiers","Access control matrix"], d:["Test 10 endpoints","Map user roles"]},
"cyber-security::Modules & Payloads": {t:"3 days", l:["Auxiliary vs exploit","Staged vs stageless"], d:["List 20 modules","Generate 3 payloads"]},
"cyber-security::Meterpreter": {t:"1 week", l:["Core commands","Pivoting basics"], d:["Get a session","Migrate processes"]},
"cyber-security::Hash Cracking": {t:"1 week", l:["Hash identification","hashcat modes"], d:["Crack 10 hashes","Identify 5 types"]},
"cyber-security::Wordlists & Rules": {t:"3 days", l:["SecLists tour","Rule-based mutations"], d:["Build a custom list","Write 3 rules"]},
"cyber-security::Linux Privesc": {t:"2 weeks", l:["Enumeration first","SUID, sudo, cron paths"], d:["Root 3 boxes","Run LinPEAS fully"]},
"cyber-security::Windows Privesc": {t:"2 weeks", l:["Windows enumeration","Service abuse"], d:["Escalate 2 boxes","Run WinPEAS"]},
"cyber-security::Platforms & Scope": {t:"2 days", l:["Reading scopes","VDP vs paid"], d:["Compare 5 programs","Pick your first target"]},
"frontend::Semantic HTML": {t:"3 days", l:["Landmarks and sections","Accessibility wins"], d:["Mark up a page semantically","Audit with a screen reader"]},
"frontend::Forms & Inputs": {t:"3 days", l:["Every input type","Validation basics"], d:["Build a full form","Validate without JS"]},
"frontend::Flexbox & Grid": {t:"1 week", l:["Flex alignment","Grid templates"], d:["Build 5 layouts","Recreate 3 designs"]},
"frontend::Responsive Design": {t:"1 week", l:["Media queries","Mobile-first flow"], d:["Make 3 pages responsive","Test on real devices"]},
"frontend::DOM Manipulation": {t:"1 week", l:["Querying the DOM","Events and delegation"], d:["Build interactive widgets","Handle 10 events"]},
"frontend::Async JS & Fetch": {t:"1 week", l:["Promises deeply","async/await patterns"], d:["Fetch 5 APIs","Handle errors well"]},
"frontend::Types & Interfaces": {t:"1 week", l:["Typing objects","Unions and generics"], d:["Type 20 functions","Fix 15 type errors"]},
"frontend::Unit Tests": {t:"3 days", l:["What to test","Assertions"], d:["Write 20 tests","Break code, watch tests"]},
"frontend::package.json": {t:"2 days", l:["Scripts and deps","Semver basics"], d:["Script 5 tasks","Audit dependencies"]},
"frontend::Build & Deploy": {t:"3 days", l:["Bundling concepts","Deploy pipelines"], d:["Deploy 2 apps","Optimize a bundle"]},
"frontend::Branching": {t:"2 days", l:["Branch workflows","Merging cleanly"], d:["Branch 5 features","Resolve conflicts"]},
"frontend::Pull Requests": {t:"2 days", l:["Good PR hygiene","Code review etiquette"], d:["Open 3 PRs","Review a peer PR"]},
"backend::Node.js": {t:"3 weeks", l:["Event loop basics","Express routing"], d:["Build a REST API","Handle 1000 requests"]},
"backend::Python": {t:"3 weeks", l:["FastAPI or Flask","Virtual environments"], d:["Build an API","Write 10 endpoints"]},
"backend::Go": {t:"4 weeks", l:["Go syntax","Concurrency basics"], d:["Build a CLI","Serve HTTP in Go"]},
"backend::Routing & Controllers": {t:"1 week", l:["RESTful design","Controller patterns"], d:["Design 10 routes","Refactor handlers"]},
"backend::Status Codes": {t:"2 days", l:["2xx, 4xx, 5xx","Error payloads"], d:["Use 10 codes correctly","Write error middleware"]},
"backend::Schema Design": {t:"1 week", l:["Normalization","Keys and constraints"], d:["Design 3 schemas","Normalize a messy one"]},
"backend::Joins & Queries": {t:"1 week", l:["JOIN types","Aggregations"], d:["Write 25 queries","Optimize 3 slow ones"]},
"backend::Password Hashing": {t:"2 days", l:["bcrypt and argon2","Salts explained"], d:["Hash 10 passwords","Benchmark cost factors"]},
"backend::Sessions vs Tokens": {t:"3 days", l:["Stateful vs stateless","Refresh token flow"], d:["Build both systems","Compare trade-offs"]},
"backend::Dockerfile": {t:"3 days", l:["Layer caching","Multi-stage builds"], d:["Write 3 Dockerfiles","Shrink an image"]},
"backend::Compose": {t:"2 days", l:["Services and networks","Volumes"], d:["Compose 3 services","Persist data"]},
"backend::Cache Patterns": {t:"3 days", l:["Cache-aside","TTL and invalidation"], d:["Cache 5 endpoints","Measure hit rates"]},
"devops::Bash Basics": {t:"1 week", l:["Scripting essentials","Error handling"], d:["Automate 5 tasks","Lint with ShellCheck"]},
"devops::SSH & Servers": {t:"3 days", l:["Key auth","Hardened sshd"], d:["Set up key login","Harden 2 servers"]},
"devops::Branching Strategies": {t:"2 days", l:["GitFlow vs trunk","Release branches"], d:["Diagram 3 strategies","Pick one for a project"]},
"devops::Rebase & Merge": {t:"3 days", l:["Interactive rebase","Merge strategies"], d:["Rebase 5 branches","Fix a messy history"]},
"devops::Workflows": {t:"1 week", l:["Triggers and jobs","Matrix builds"], d:["Build 3 pipelines","Add status badges"]},
"devops::Secrets & Envs": {t:"2 days", l:["Encrypted secrets","Environments"], d:["Store 5 secrets","Rotate one safely"]},
"devops::Images & Containers": {t:"1 week", l:["Image layers","Running containers"], d:["Build 5 images","Debug a crash loop"]},
"devops::Volumes & Networks": {t:"3 days", l:["Persisting data","Container networking"], d:["Persist a database","Link 4 containers"]},
"devops::Pods & Deployments": {t:"2 weeks", l:["Pod specs","Rolling updates"], d:["Deploy to k3s","Roll back a release"]},
"devops::Services & Ingress": {t:"1 week", l:["Service types","Ingress rules"], d:["Expose 3 apps","Set up TLS"]},
"devops::EC2 & S3": {t:"1 week", l:["Instances and AMIs","Buckets and policies"], d:["Launch an instance","Host a static site"]},
"devops::IAM Basics": {t:"3 days", l:["Users and roles","Least privilege"], d:["Create 3 IAM users","Write a tight policy"]},
"devops::State & Resources": {t:"1 week", l:["State files","Resource graph"], d:["Manage 10 resources","Recover lost state"]},
"devops::Modules": {t:"3 days", l:["Module structure","Versioning"], d:["Write 2 modules","Reuse across envs"]},
"devops::Prometheus & Grafana": {t:"1 week", l:["Metrics and queries","Dashboards"], d:["Scrape 3 targets","Build 2 dashboards"]},
"devops::Centralized Logging": {t:"3 days", l:["Log aggregation","Searching logs"], d:["Ship logs centrally","Find an incident"]},
"python::Data Types": {t:"3 days", l:["Lists, dicts, sets, tuples","Comprehensions"], d:["Solve 20 problems","Rewrite loops as comprehensions"]},
"python::Control Flow": {t:"3 days", l:["Conditionals","Loops and iteration"], d:["Solve 20 problems","Trace 10 programs"]},
"python::Classes": {t:"1 week", l:["Attributes and methods","Inheritance"], d:["Model 3 real things","Refactor to classes"]},
"python::Imports & Packages": {t:"2 days", l:["Module system","__init__ files"], d:["Package a project","Fix circular imports"]},
"python::REST Clients": {t:"3 days", l:["requests deep dive","Auth patterns"], d:["Build 3 API clients","Handle pagination"]},
"python::JSON Handling": {t:"2 days", l:["Parsing and dumping","Nested data"], d:["Parse 5 payloads","Validate schemas"]},
"python::File Automation": {t:"3 days", l:["pathlib mastery","Batch operations"], d:["Organize 500 files","Write a backup tool"]},
"python::Web Scraping": {t:"1 week", l:["BeautifulSoup","Respectful scraping"], d:["Scrape 3 sites","Handle anti-bot basics"]},
"python::Routing": {t:"3 days", l:["Path operations","Request models"], d:["Build 10 routes","Document with OpenAPI"]},
"python::Validation": {t:"3 days", l:["Pydantic v2","Custom validators"], d:["Validate 10 payloads","Write custom types"]},
"python::DataFrames": {t:"1 week", l:["Selecting and filtering","GroupBy"], d:["Analyze a dataset","Answer 10 questions"]},
"python::Plotting": {t:"3 days", l:["matplotlib basics","Chart types"], d:["Make 8 chart types","Style a dashboard"]},
"bug-bounty::Methods & Status Codes": {t:"2 days", l:["All HTTP methods","Status code classes"], d:["Try 7 methods","Map codes to bugs"]},
"bug-bounty::Headers & Cookies": {t:"3 days", l:["Security headers","Cookie flags"], d:["Audit 10 sites headers","Find 3 misconfigs"]},
"bug-bounty::DOM XSS Sinks": {t:"1 week", l:["Sink catalog","Source to sink tracing"], d:["Audit 5 JS bundles","Write 3 payloads"]},
"bug-bounty::Prototype Pollution": {t:"1 week", l:["Pollution vectors","Gadget hunting"], d:["Pollute 2 lab apps","Find a gadget"]},
"bug-bounty::Passive Enum": {t:"3 days", l:["OSINT sources","Automation"], d:["Enum 3 targets","Compare 4 tools"]},
"bug-bounty::DNS Bruteforcing": {t:"2 days", l:["Wordlist strategy","Resolvers"], d:["Bruteforce a scope","Tune wordlists"]},
"bug-bounty::Fuzzing": {t:"3 days", l:["ffuf modes","Status code reading"], d:["Fuzz 5 targets","Find hidden paths"]},
"bug-bounty::Wordlists": {t:"2 days", l:["SecLists tour","Targeted lists"], d:["Build a custom list","Prune dead entries"]},
"bug-bounty::IDOR Patterns": {t:"3 days", l:["Numeric and UUID IDs","Bulk endpoints"], d:["Test 15 endpoints","Document patterns"]},
"bug-bounty::Forced Browsing": {t:"2 days", l:["Predictable paths","Backup files"], d:["Find 5 hidden files","Check /.git/"]},
"bug-bounty::Blind SSRF": {t:"1 week", l:["Out-of-band techniques","Cloud metadata"], d:["Exploit 2 blind labs","Use a collaborator"]},
"bug-bounty::XXE Payloads": {t:"3 days", l:["Classic XXE","Blind variants"], d:["Read /etc/passwd in lab","Exfiltrate via OOB"]},
"bug-bounty::Single-Endpoint Races": {t:"3 days", l:["Race windows","Turbo Intruder"], d:["Win 2 race labs","Script a racer"]},
"bug-bounty::Program Recon": {t:"3 days", l:["Scope analysis","Asset mapping"], d:["Recon 2 programs","Rank by attack surface"]},
"bug-bounty::Impact & Severity": {t:"2 days", l:["CVSS basics","Writing impact"], d:["Score 5 bugs","Rewrite 3 reports"]},
"networking::CIDR Notation": {t:"3 days", l:["Slash to mask","Range calculation"], d:["Convert 20 notations","Carve 8 subnets"]},
"networking::Subnet Practice": {t:"1 week", l:["Speed techniques","VLSM"], d:["Do 50 drills","Beat your best time"]},
"networking::Record Types": {t:"2 days", l:["A, AAAA, CNAME, MX, TXT","When each is used"], d:["Query all types","Explain a dig output"]},
"networking::DNS Security": {t:"3 days", l:["Cache poisoning","DNSSEC and DoH"], d:["Spot spoofing signs","Enable DoH"]},
"networking::Routing Tables": {t:"3 days", l:["Reading routes","Longest prefix match"], d:["Read 3 tables","Predict packet paths"]},
"networking::VLANs": {t:"3 days", l:["Tagging 101","Segmentation wins"], d:["Design 4 VLANs","Explain trunk ports"]},
"networking::Capture Filters": {t:"2 days", l:["BPF syntax","Capture smart"], d:["Write 8 filters","Capture 1 host only"]},
"networking::Traffic Analysis": {t:"1 week", l:["Anomaly spotting","Protocol deep dives"], d:["Solve 5 challenges","Find C2 traffic"]},
"networking::iptables Basics": {t:"3 days", l:["Chains and rules","Default policies"], d:["Write 10 rules","Lock down a host"]},
"networking::NAT Types": {t:"2 days", l:["SNAT vs DNAT","Port forwarding"], d:["Forward 3 ports","Diagram your NAT"]},
"cloud::Policies": {t:"3 days", l:["Policy JSON","Effect and actions"], d:["Write 5 policies","Test with the simulator"]},
"cloud::Roles & Trust": {t:"3 days", l:["Trust policies","Cross-account roles"], d:["Create 2 roles","Break and fix trust"]},
"cloud::Bucket Policies": {t:"2 days", l:["Policy vs ACL","Public access blocks"], d:["Audit 5 buckets","Write a strict policy"]},
"cloud::Encryption": {t:"2 days", l:["SSE-S3 vs SSE-KMS","In-transit TLS"], d:["Enable encryption","Rotate a KMS key"]},
"cloud::Public Resources": {t:"3 days", l:["Common exposures","How attackers scan"], d:["Audit an account","Close 5 exposures"]},
"cloud::Leaked Keys": {t:"2 days", l:["GitHub dorking","Key patterns"], d:["Search 3 patterns","Rotate a leaked key"]},
"cloud::Running Audits": {t:"3 days", l:["ScoutSuite flow","Prowler checks"], d:["Audit a lab account","Triage 30 findings"]},
"cloud::Remediation": {t:"3 days", l:["Fix priority order","Guardrails"], d:["Fix 10 findings","Write a runbook"]},
};
console.log("depth pack complete");
